[opener]
pdf = [
  { run = "zathura \"$@\"", desc = "Zathura", block = false }
]

epub = [
  { run = "zathura \"$@\"", desc = "Zathura", block = false }
]

[open]
rules = [
  { mime = "application/pdf", use = "pdf" },
  { mime = "application/epub+zip", use = "epub" }
]

[preview]
max_width  = 600
max_height = 400
